/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author STEFGIN
 */
public class Acceso extends javax.swing.JFrame {

    /**
     * Creates new form Acceso
     */
    public Acceso() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        lblSistemaAcceso = new javax.swing.JLabel();
        panAccesoAdmin = new javax.swing.JPanel();
        lblUsuarioAdmin = new javax.swing.JLabel();
        lblPasswordAdmin = new javax.swing.JLabel();
        btnIngresarAdmin = new javax.swing.JButton();
        txtUsuarioAdmin = new javax.swing.JTextField();
        txtPPaswordAdmin = new javax.swing.JPasswordField();
        panAccesoUsuariosGeneral = new javax.swing.JPanel();
        lblUsuarioGeneral = new javax.swing.JLabel();
        lblPasswordUsuarioGeneral = new javax.swing.JLabel();
        txtUsuarioGeneral = new javax.swing.JTextField();
        btnIngresarUsuarioGeneral = new javax.swing.JButton();
        txtPPassword = new javax.swing.JPasswordField();
        lblImgAdmin = new javax.swing.JLabel();
        lblImgUser = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnSalirAcceso = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondo.setBackground(new java.awt.Color(255, 255, 255));
        panFondo.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema de Acceso"));

        lblSistemaAcceso.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSistemaAcceso.setForeground(new java.awt.Color(204, 0, 0));
        lblSistemaAcceso.setText("Sistema Acceso");

        panAccesoAdmin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Administrador", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblUsuarioAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuarioAdmin.setText("Usuario");

        lblPasswordAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPasswordAdmin.setText("Password");

        btnIngresarAdmin.setBackground(new java.awt.Color(204, 204, 204));
        btnIngresarAdmin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresarAdmin.setText("Ingresar");

        txtUsuarioAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioAdminActionPerformed(evt);
            }
        });

        txtPPaswordAdmin.setText("jPasswordField1");

        javax.swing.GroupLayout panAccesoAdminLayout = new javax.swing.GroupLayout(panAccesoAdmin);
        panAccesoAdmin.setLayout(panAccesoAdminLayout);
        panAccesoAdminLayout.setHorizontalGroup(
            panAccesoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccesoAdminLayout.createSequentialGroup()
                .addGroup(panAccesoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAccesoAdminLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(panAccesoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPasswordAdmin)
                            .addComponent(lblUsuarioAdmin))
                        .addGap(32, 32, 32)
                        .addGroup(panAccesoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUsuarioAdmin)
                            .addComponent(txtPPaswordAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                    .addGroup(panAccesoAdminLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(btnIngresarAdmin)))
                .addContainerGap())
        );
        panAccesoAdminLayout.setVerticalGroup(
            panAccesoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccesoAdminLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(panAccesoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioAdmin)
                    .addComponent(txtUsuarioAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(panAccesoAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordAdmin)
                    .addComponent(txtPPaswordAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnIngresarAdmin)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        panAccesoUsuariosGeneral.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Usuarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblUsuarioGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsuarioGeneral.setText("Usuario");

        lblPasswordUsuarioGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPasswordUsuarioGeneral.setText("Password");

        txtUsuarioGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioGeneralActionPerformed(evt);
            }
        });

        btnIngresarUsuarioGeneral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnIngresarUsuarioGeneral.setText("Ingresar");

        txtPPassword.setText("jPasswordField2");

        javax.swing.GroupLayout panAccesoUsuariosGeneralLayout = new javax.swing.GroupLayout(panAccesoUsuariosGeneral);
        panAccesoUsuariosGeneral.setLayout(panAccesoUsuariosGeneralLayout);
        panAccesoUsuariosGeneralLayout.setHorizontalGroup(
            panAccesoUsuariosGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccesoUsuariosGeneralLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(panAccesoUsuariosGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPasswordUsuarioGeneral)
                    .addComponent(lblUsuarioGeneral))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(panAccesoUsuariosGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUsuarioGeneral)
                    .addComponent(txtPPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAccesoUsuariosGeneralLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresarUsuarioGeneral)
                .addGap(98, 98, 98))
        );
        panAccesoUsuariosGeneralLayout.setVerticalGroup(
            panAccesoUsuariosGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAccesoUsuariosGeneralLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(panAccesoUsuariosGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsuarioGeneral)
                    .addComponent(txtUsuarioGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(panAccesoUsuariosGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPasswordUsuarioGeneral)
                    .addComponent(txtPPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(btnIngresarUsuarioGeneral)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        lblImgAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/admin150.png"))); // NOI18N

        lblImgUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/user150.png"))); // NOI18N

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFT.png"))); // NOI18N

        btnSalirAcceso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirAcceso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Xsalir.png"))); // NOI18N
        btnSalirAcceso.setText("Salir");

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAccesoAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panAccesoUsuariosGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(lblImgAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                        .addComponent(lblImgUser)
                        .addGap(79, 79, 79))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblSistemaAcceso)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSalirAcceso)
                        .addGap(21, 21, 21))))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(0, 74, Short.MAX_VALUE)
                        .addComponent(lblImgAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panAccesoAdmin, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panAccesoUsuariosGeneral, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFondoLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(lblSistemaAcceso))
                            .addComponent(btnSalirAcceso))
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFondoLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(lblImgUser))
                            .addGroup(panFondoLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblLogo)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioAdminActionPerformed

    private void txtUsuarioGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioGeneralActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioGeneralActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acceso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acceso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresarAdmin;
    private javax.swing.JButton btnIngresarUsuarioGeneral;
    private javax.swing.JButton btnSalirAcceso;
    private javax.swing.JLabel lblImgAdmin;
    private javax.swing.JLabel lblImgUser;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblPasswordAdmin;
    private javax.swing.JLabel lblPasswordUsuarioGeneral;
    private javax.swing.JLabel lblSistemaAcceso;
    private javax.swing.JLabel lblUsuarioAdmin;
    private javax.swing.JLabel lblUsuarioGeneral;
    private javax.swing.JPanel panAccesoAdmin;
    private javax.swing.JPanel panAccesoUsuariosGeneral;
    private javax.swing.JPanel panFondo;
    private javax.swing.JPasswordField txtPPassword;
    private javax.swing.JPasswordField txtPPaswordAdmin;
    private javax.swing.JTextField txtUsuarioAdmin;
    private javax.swing.JTextField txtUsuarioGeneral;
    // End of variables declaration//GEN-END:variables
}
