/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author STEFGIN
 */
public class Almacen extends javax.swing.JFrame {

    /**
     * Creates new form Inventario
     */
    public Almacen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        lblSistemaAlmacen = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        panBuscarEditarProducto = new javax.swing.JPanel();
        lblIdProductoBuscar = new javax.swing.JLabel();
        txtPrecioProductoBuscar = new javax.swing.JTextField();
        lblPrecioProductoBuscar = new javax.swing.JLabel();
        lblNombreProductoBuscar = new javax.swing.JLabel();
        lblDescripcionBuscar = new javax.swing.JLabel();
        lblCantidadProductoBuscar = new javax.swing.JLabel();
        txtIdProductoBuscar = new javax.swing.JTextField();
        txtCantidadProductoBuscar = new javax.swing.JTextField();
        txtNombreProductoBuscar = new javax.swing.JTextField();
        txtDescripcionProductoBuscar = new javax.swing.JTextField();
        btnBuscarProducto = new javax.swing.JButton();
        btnEditarProducto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtConsultarProductos = new javax.swing.JTable();
        panAgregarProducto1 = new javax.swing.JPanel();
        lblIdProductoAgregar = new javax.swing.JLabel();
        txtPrecioProductoAgregar = new javax.swing.JTextField();
        lblPrecioProductoAgregar = new javax.swing.JLabel();
        lblNombreProductoAgregar = new javax.swing.JLabel();
        lblDescripcionProductoAgregar = new javax.swing.JLabel();
        lblCantidadProductoAgregar = new javax.swing.JLabel();
        txtIdProductoAgregar = new javax.swing.JTextField();
        txtCantidadProductoAgregar = new javax.swing.JTextField();
        txtNombreProductoAgregar = new javax.swing.JTextField();
        txtDescripcionProductoAgregar = new javax.swing.JTextField();
        btnAgregarProducto = new javax.swing.JButton();
        btnVerPDFalmacen = new javax.swing.JButton();
        btnConsultarProductos = new javax.swing.JButton();
        btnImprimir = new javax.swing.JButton();
        panEliminarProducto = new javax.swing.JPanel();
        lblNombreProductoEliminar = new javax.swing.JLabel();
        lblIdProductoEliminar = new javax.swing.JLabel();
        txtIdProductoEliminar = new javax.swing.JTextField();
        txtNombreProductoEliminar = new javax.swing.JTextField();
        btnEliminarProducto = new javax.swing.JButton();
        btnSalirAlmacen = new javax.swing.JButton();
        btnRegresarAlmacen = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondo.setBackground(new java.awt.Color(255, 255, 255));
        panFondo.setPreferredSize(new java.awt.Dimension(800, 700));

        lblSistemaAlmacen.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSistemaAlmacen.setForeground(new java.awt.Color(204, 0, 0));
        lblSistemaAlmacen.setText("Almacen");

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFT.png"))); // NOI18N

        panBuscarEditarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar y/o Editar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblIdProductoBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdProductoBuscar.setText("IdProducto");

        txtPrecioProductoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoBuscarActionPerformed(evt);
            }
        });

        lblPrecioProductoBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecioProductoBuscar.setText("Precio");

        lblNombreProductoBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreProductoBuscar.setText("Nombre");

        lblDescripcionBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDescripcionBuscar.setText("Descripcion");

        lblCantidadProductoBuscar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantidadProductoBuscar.setText("Cantidad");

        txtIdProductoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoBuscarActionPerformed(evt);
            }
        });

        txtCantidadProductoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoBuscarActionPerformed(evt);
            }
        });

        txtNombreProductoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoBuscarActionPerformed(evt);
            }
        });

        txtDescripcionProductoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionProductoBuscarActionPerformed(evt);
            }
        });

        btnBuscarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarProducto.setText("Buscar");

        btnEditarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditarProducto.setText("Editar");

        javax.swing.GroupLayout panBuscarEditarProductoLayout = new javax.swing.GroupLayout(panBuscarEditarProducto);
        panBuscarEditarProducto.setLayout(panBuscarEditarProductoLayout);
        panBuscarEditarProductoLayout.setHorizontalGroup(
            panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuscarEditarProductoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuscarEditarProductoLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPrecioProductoBuscar)
                            .addComponent(lblDescripcionBuscar)
                            .addComponent(lblCantidadProductoBuscar))
                        .addGap(37, 37, 37)
                        .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCantidadProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPrecioProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcionProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panBuscarEditarProductoLayout.createSequentialGroup()
                        .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdProductoBuscar)
                            .addComponent(lblNombreProductoBuscar))
                        .addGap(38, 38, 38)
                        .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscarProducto)
                    .addComponent(btnEditarProducto))
                .addGap(0, 25, Short.MAX_VALUE))
        );
        panBuscarEditarProductoLayout.setVerticalGroup(
            panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuscarEditarProductoLayout.createSequentialGroup()
                .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuscarEditarProductoLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtIdProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdProductoBuscar))
                        .addGap(18, 18, 18))
                    .addGroup(panBuscarEditarProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBuscarProducto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreProductoBuscar)
                    .addComponent(btnEditarProducto))
                .addGap(18, 18, 18)
                .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionBuscar)
                    .addComponent(txtDescripcionProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioProductoBuscar)
                    .addComponent(txtPrecioProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panBuscarEditarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadProductoBuscar)
                    .addComponent(txtCantidadProductoBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        jtConsultarProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Producto", "Nombre", "Descripcion", "Precio", "Cantidad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtConsultarProductos);

        panAgregarProducto1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblIdProductoAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdProductoAgregar.setText("IdProducto");

        txtPrecioProductoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoAgregarActionPerformed(evt);
            }
        });

        lblPrecioProductoAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecioProductoAgregar.setText("Precio");

        lblNombreProductoAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreProductoAgregar.setText("Nombre");

        lblDescripcionProductoAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDescripcionProductoAgregar.setText("Descripcion");

        lblCantidadProductoAgregar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantidadProductoAgregar.setText("Cantidad");

        txtIdProductoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoAgregarActionPerformed(evt);
            }
        });

        txtCantidadProductoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadProductoAgregarActionPerformed(evt);
            }
        });

        txtNombreProductoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoAgregarActionPerformed(evt);
            }
        });

        txtDescripcionProductoAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionProductoAgregarActionPerformed(evt);
            }
        });

        btnAgregarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarProducto.setText("Agregar Producto");

        javax.swing.GroupLayout panAgregarProducto1Layout = new javax.swing.GroupLayout(panAgregarProducto1);
        panAgregarProducto1.setLayout(panAgregarProducto1Layout);
        panAgregarProducto1Layout.setHorizontalGroup(
            panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarProducto1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panAgregarProducto1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPrecioProductoAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDescripcionProductoAgregar, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCantidadProductoAgregar, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(33, 33, 33)
                        .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPrecioProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDescripcionProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCantidadProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panAgregarProducto1Layout.createSequentialGroup()
                        .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdProductoAgregar)
                            .addComponent(lblNombreProductoAgregar))
                        .addGap(31, 31, 31)
                        .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombreProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(9, 9, 9))
            .addGroup(panAgregarProducto1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(btnAgregarProducto)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panAgregarProducto1Layout.setVerticalGroup(
            panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarProducto1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProductoAgregar))
                .addGap(18, 18, 18)
                .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreProductoAgregar))
                .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAgregarProducto1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtDescripcionProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panAgregarProducto1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblDescripcionProductoAgregar)))
                .addGap(18, 18, 18)
                .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioProductoAgregar)
                    .addComponent(txtPrecioProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panAgregarProducto1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadProductoAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidadProductoAgregar))
                .addGap(14, 14, 14)
                .addComponent(btnAgregarProducto)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVerPDFalmacen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerPDFalmacen.setText("Ver PDF");

        btnConsultarProductos.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarProductos.setText("Consultar");

        btnImprimir.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImprimir.setText("Imprimir");

        panEliminarProducto.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblNombreProductoEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreProductoEliminar.setText("Nombre");

        lblIdProductoEliminar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdProductoEliminar.setText("idProducto");

        txtIdProductoEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoEliminarActionPerformed(evt);
            }
        });

        btnEliminarProducto.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarProducto.setText("Eliminar");

        javax.swing.GroupLayout panEliminarProductoLayout = new javax.swing.GroupLayout(panEliminarProducto);
        panEliminarProducto.setLayout(panEliminarProductoLayout);
        panEliminarProductoLayout.setHorizontalGroup(
            panEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarProductoLayout.createSequentialGroup()
                .addGroup(panEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEliminarProductoLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdProductoEliminar)
                            .addComponent(lblNombreProductoEliminar))
                        .addGap(58, 58, 58)
                        .addGroup(panEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdProductoEliminar)
                            .addComponent(txtNombreProductoEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                    .addGroup(panEliminarProductoLayout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(btnEliminarProducto)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panEliminarProductoLayout.setVerticalGroup(
            panEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEliminarProductoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProductoEliminar)
                    .addComponent(txtIdProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panEliminarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProductoEliminar)
                    .addComponent(txtNombreProductoEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(btnEliminarProducto)
                .addGap(23, 23, 23))
        );

        btnSalirAlmacen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Xsalir.png"))); // NOI18N
        btnSalirAlmacen.setText("Salir");

        btnRegresarAlmacen.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresarAlmacen.setText("Regresar");
        btnRegresarAlmacen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarAlmacenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addComponent(panBuscarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panAgregarProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegresarAlmacen))
                        .addGap(18, 18, 18)
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panFondoLayout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblSistemaAlmacen)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblLogo)
                                .addGap(18, 18, 18)
                                .addComponent(btnSalirAlmacen))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                                .addComponent(btnConsultarProductos)
                                .addGap(53, 53, 53)
                                .addComponent(btnVerPDFalmacen)
                                .addGap(60, 60, 60)
                                .addComponent(btnImprimir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                        .addComponent(btnRegresarAlmacen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(panAgregarProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSistemaAlmacen)
                            .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSalirAlmacen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarProductos)
                            .addComponent(btnVerPDFalmacen)
                            .addComponent(btnImprimir))))
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBuscarEditarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(panEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioProductoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoBuscarActionPerformed

    private void txtIdProductoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoBuscarActionPerformed

    private void txtCantidadProductoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoBuscarActionPerformed

    private void txtNombreProductoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoBuscarActionPerformed

    private void txtDescripcionProductoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionProductoBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionProductoBuscarActionPerformed

    private void txtPrecioProductoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoAgregarActionPerformed

    private void txtIdProductoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoAgregarActionPerformed

    private void txtCantidadProductoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadProductoAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadProductoAgregarActionPerformed

    private void txtNombreProductoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoAgregarActionPerformed

    private void txtDescripcionProductoAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionProductoAgregarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionProductoAgregarActionPerformed

    private void txtIdProductoEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoEliminarActionPerformed

    private void btnRegresarAlmacenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarAlmacenActionPerformed
         MenuGeneral ventanaMenuGeneral = new MenuGeneral();
        ventanaMenuGeneral.setVisible(true);//visualizar
        hide();//ocultar
    }//GEN-LAST:event_btnRegresarAlmacenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Almacen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Almacen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarProducto;
    private javax.swing.JButton btnBuscarProducto;
    private javax.swing.JButton btnConsultarProductos;
    private javax.swing.JButton btnEditarProducto;
    private javax.swing.JButton btnEliminarProducto;
    private javax.swing.JButton btnImprimir;
    private javax.swing.JButton btnRegresarAlmacen;
    private javax.swing.JButton btnSalirAlmacen;
    private javax.swing.JButton btnVerPDFalmacen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtConsultarProductos;
    private javax.swing.JLabel lblCantidadProductoAgregar;
    private javax.swing.JLabel lblCantidadProductoBuscar;
    private javax.swing.JLabel lblDescripcionBuscar;
    private javax.swing.JLabel lblDescripcionProductoAgregar;
    private javax.swing.JLabel lblIdProductoAgregar;
    private javax.swing.JLabel lblIdProductoBuscar;
    private javax.swing.JLabel lblIdProductoEliminar;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreProductoAgregar;
    private javax.swing.JLabel lblNombreProductoBuscar;
    private javax.swing.JLabel lblNombreProductoEliminar;
    private javax.swing.JLabel lblPrecioProductoAgregar;
    private javax.swing.JLabel lblPrecioProductoBuscar;
    private javax.swing.JLabel lblSistemaAlmacen;
    private javax.swing.JPanel panAgregarProducto1;
    private javax.swing.JPanel panBuscarEditarProducto;
    private javax.swing.JPanel panEliminarProducto;
    private javax.swing.JPanel panFondo;
    private javax.swing.JTextField txtCantidadProductoAgregar;
    private javax.swing.JTextField txtCantidadProductoBuscar;
    private javax.swing.JTextField txtDescripcionProductoAgregar;
    private javax.swing.JTextField txtDescripcionProductoBuscar;
    private javax.swing.JTextField txtIdProductoAgregar;
    private javax.swing.JTextField txtIdProductoBuscar;
    private javax.swing.JTextField txtIdProductoEliminar;
    private javax.swing.JTextField txtNombreProductoAgregar;
    private javax.swing.JTextField txtNombreProductoBuscar;
    private javax.swing.JTextField txtNombreProductoEliminar;
    private javax.swing.JTextField txtPrecioProductoAgregar;
    private javax.swing.JTextField txtPrecioProductoBuscar;
    // End of variables declaration//GEN-END:variables
}
