/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author STEFGIN
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Ventas
     */
    public Venta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panFondo = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        lblSistemaVenta = new javax.swing.JLabel();
        panAgregarProductosVenta = new javax.swing.JPanel();
        txtCantidadProductosVenta = new javax.swing.JLabel();
        lblIdProductoAgregarVenta = new javax.swing.JLabel();
        txtIdProductoVenta = new javax.swing.JTextField();
        txtCantidadAgregarVenta = new javax.swing.JTextField();
        btnAgregarVenta = new javax.swing.JButton();
        panBuscarEditarProductoVenta = new javax.swing.JPanel();
        lblIdProductoBuscarVenta = new javax.swing.JLabel();
        txtPrecioProductoBuscarVenta = new javax.swing.JTextField();
        lblPrecioProductoBuscarVenta = new javax.swing.JLabel();
        lblNombreProductoBuscarVenta = new javax.swing.JLabel();
        lblDescripcionBuscarVenta = new javax.swing.JLabel();
        lblCantidadProductoBuscarVenta = new javax.swing.JLabel();
        txtIdProductoBuscarVenta = new javax.swing.JTextField();
        txtCantidadBuscarVenta = new javax.swing.JTextField();
        txtNombreProductoBuscarVenta = new javax.swing.JTextField();
        txtDescripcionProductoBuscarVenta = new javax.swing.JTextField();
        btnBuscarProductoVenta = new javax.swing.JButton();
        btnEditarProductoVenta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtVentas = new javax.swing.JTable();
        panEliminarProductoVenta = new javax.swing.JPanel();
        lblNombreProductoEliminarVenta = new javax.swing.JLabel();
        lblIdProductoEliminarVenta = new javax.swing.JLabel();
        txtIdProductoEliminarVenta = new javax.swing.JTextField();
        txtNombreProductoEliminarVenta = new javax.swing.JTextField();
        btnEliminarProductoVenta = new javax.swing.JButton();
        btnConsultarVenta = new javax.swing.JButton();
        btnVerPDFventa = new javax.swing.JButton();
        btnImprimirVenta = new javax.swing.JButton();
        btnSalirVenta = new javax.swing.JButton();
        btnRegresarVenta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panFondo.setBackground(new java.awt.Color(255, 255, 255));
        panFondo.setPreferredSize(new java.awt.Dimension(700, 650));

        lblLogo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logoFT.png"))); // NOI18N

        lblSistemaVenta.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblSistemaVenta.setForeground(new java.awt.Color(204, 0, 0));
        lblSistemaVenta.setText("Sistema Venta");

        panAgregarProductosVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar Productos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        txtCantidadProductosVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtCantidadProductosVenta.setText("Cantidad");

        lblIdProductoAgregarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdProductoAgregarVenta.setText("idProducto");

        btnAgregarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnAgregarVenta.setText("Agregar a Nota");

        javax.swing.GroupLayout panAgregarProductosVentaLayout = new javax.swing.GroupLayout(panAgregarProductosVenta);
        panAgregarProductosVenta.setLayout(panAgregarProductosVentaLayout);
        panAgregarProductosVentaLayout.setHorizontalGroup(
            panAgregarProductosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAgregarProductosVentaLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(panAgregarProductosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIdProductoAgregarVenta)
                    .addGroup(panAgregarProductosVentaLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(txtCantidadProductosVenta)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(panAgregarProductosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCantidadAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIdProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44))
            .addGroup(panAgregarProductosVentaLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnAgregarVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAgregarProductosVentaLayout.setVerticalGroup(
            panAgregarProductosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAgregarProductosVentaLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(panAgregarProductosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProductoAgregarVenta)
                    .addComponent(txtIdProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panAgregarProductosVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidadProductosVenta)
                    .addComponent(txtCantidadAgregarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarVenta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panBuscarEditarProductoVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar y/o Editar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblIdProductoBuscarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdProductoBuscarVenta.setText("IdProducto");

        txtPrecioProductoBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioProductoBuscarVentaActionPerformed(evt);
            }
        });

        lblPrecioProductoBuscarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPrecioProductoBuscarVenta.setText("Precio");

        lblNombreProductoBuscarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreProductoBuscarVenta.setText("Nombre");

        lblDescripcionBuscarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblDescripcionBuscarVenta.setText("Descripcion");

        lblCantidadProductoBuscarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblCantidadProductoBuscarVenta.setText("Cantidad");

        txtIdProductoBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoBuscarVentaActionPerformed(evt);
            }
        });

        txtCantidadBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadBuscarVentaActionPerformed(evt);
            }
        });

        txtNombreProductoBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreProductoBuscarVentaActionPerformed(evt);
            }
        });

        txtDescripcionProductoBuscarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionProductoBuscarVentaActionPerformed(evt);
            }
        });

        btnBuscarProductoVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnBuscarProductoVenta.setText("Buscar");

        btnEditarProductoVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEditarProductoVenta.setText("Editar cantidad");

        javax.swing.GroupLayout panBuscarEditarProductoVentaLayout = new javax.swing.GroupLayout(panBuscarEditarProductoVenta);
        panBuscarEditarProductoVenta.setLayout(panBuscarEditarProductoVentaLayout);
        panBuscarEditarProductoVentaLayout.setHorizontalGroup(
            panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuscarEditarProductoVentaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panBuscarEditarProductoVentaLayout.createSequentialGroup()
                        .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdProductoBuscarVenta)
                            .addComponent(lblNombreProductoBuscarVenta))
                        .addGap(38, 38, 38)
                        .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtNombreProductoBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIdProductoBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panBuscarEditarProductoVentaLayout.createSequentialGroup()
                            .addComponent(btnBuscarProductoVenta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnEditarProductoVenta))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panBuscarEditarProductoVentaLayout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblPrecioProductoBuscarVenta)
                                .addComponent(lblDescripcionBuscarVenta)
                                .addComponent(lblCantidadProductoBuscarVenta))
                            .addGap(37, 37, 37)
                            .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtCantidadBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtPrecioProductoBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtDescripcionProductoBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        panBuscarEditarProductoVentaLayout.setVerticalGroup(
            panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBuscarEditarProductoVentaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdProductoBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProductoBuscarVenta))
                .addGap(18, 18, 18)
                .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreProductoBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreProductoBuscarVenta))
                .addGap(18, 18, 18)
                .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDescripcionBuscarVenta)
                    .addComponent(txtDescripcionProductoBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecioProductoBuscarVenta)
                    .addComponent(txtPrecioProductoBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadProductoBuscarVenta)
                    .addComponent(txtCantidadBuscarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panBuscarEditarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditarProductoVenta)
                    .addComponent(btnBuscarProductoVenta))
                .addGap(10, 10, 10))
        );

        jtVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Producto", "Cantidad", "Precio", "Subtotal"
            }
        ));
        jScrollPane1.setViewportView(jtVentas);

        panEliminarProductoVenta.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Eliminar Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        lblNombreProductoEliminarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNombreProductoEliminarVenta.setText("Nombre");

        lblIdProductoEliminarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblIdProductoEliminarVenta.setText("idProducto");

        txtIdProductoEliminarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdProductoEliminarVentaActionPerformed(evt);
            }
        });

        btnEliminarProductoVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEliminarProductoVenta.setText("Eliminar Producto");

        javax.swing.GroupLayout panEliminarProductoVentaLayout = new javax.swing.GroupLayout(panEliminarProductoVenta);
        panEliminarProductoVenta.setLayout(panEliminarProductoVentaLayout);
        panEliminarProductoVentaLayout.setHorizontalGroup(
            panEliminarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panEliminarProductoVentaLayout.createSequentialGroup()
                .addGroup(panEliminarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panEliminarProductoVentaLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(panEliminarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblIdProductoEliminarVenta)
                            .addComponent(lblNombreProductoEliminarVenta))
                        .addGap(58, 58, 58)
                        .addGroup(panEliminarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtIdProductoEliminarVenta)
                            .addComponent(txtNombreProductoEliminarVenta, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)))
                    .addGroup(panEliminarProductoVentaLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnEliminarProductoVenta)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panEliminarProductoVentaLayout.setVerticalGroup(
            panEliminarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panEliminarProductoVentaLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(panEliminarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdProductoEliminarVenta)
                    .addComponent(txtIdProductoEliminarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panEliminarProductoVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreProductoEliminarVenta)
                    .addComponent(txtNombreProductoEliminarVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnEliminarProductoVenta)
                .addGap(21, 21, 21))
        );

        btnConsultarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnConsultarVenta.setText("Consultar");

        btnVerPDFventa.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnVerPDFventa.setText("VerPDF");

        btnImprimirVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImprimirVenta.setText("Imprimir");

        btnSalirVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSalirVenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Xsalir.png"))); // NOI18N
        btnSalirVenta.setText("Salir");

        btnRegresarVenta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnRegresarVenta.setText("Regresar");
        btnRegresarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarVentaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panFondoLayout = new javax.swing.GroupLayout(panFondo);
        panFondo.setLayout(panFondoLayout);
        panFondoLayout.setHorizontalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFondoLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(panBuscarEditarProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panFondoLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(lblLogo)))
                        .addGap(8, 8, 8))
                    .addComponent(panAgregarProductosVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(panEliminarProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panFondoLayout.createSequentialGroup()
                                .addComponent(btnConsultarVenta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVerPDFventa)
                                .addGap(82, 82, 82)
                                .addComponent(btnImprimirVenta))
                            .addGroup(panFondoLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblSistemaVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegresarVenta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSalirVenta)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panFondoLayout.setVerticalGroup(
            panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panFondoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblSistemaVenta)
                        .addComponent(btnSalirVenta)
                        .addComponent(btnRegresarVenta)))
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(panFondoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(panAgregarProductosVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panBuscarEditarProductoVenta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panFondoLayout.createSequentialGroup()
                        .addGroup(panFondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnConsultarVenta)
                            .addComponent(btnVerPDFventa)
                            .addComponent(btnImprimirVenta))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panEliminarProductoVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, 783, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panFondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPrecioProductoBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioProductoBuscarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioProductoBuscarVentaActionPerformed

    private void txtIdProductoBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoBuscarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoBuscarVentaActionPerformed

    private void txtCantidadBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadBuscarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadBuscarVentaActionPerformed

    private void txtNombreProductoBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreProductoBuscarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreProductoBuscarVentaActionPerformed

    private void txtDescripcionProductoBuscarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionProductoBuscarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionProductoBuscarVentaActionPerformed

    private void txtIdProductoEliminarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdProductoEliminarVentaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdProductoEliminarVentaActionPerformed

    private void btnRegresarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarVentaActionPerformed
         MenuGeneral ventanaMenuGeneral = new MenuGeneral();
        ventanaMenuGeneral.setVisible(true);//visualizar
        hide();//ocultar
    }//GEN-LAST:event_btnRegresarVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarVenta;
    private javax.swing.JButton btnBuscarProductoVenta;
    private javax.swing.JButton btnConsultarVenta;
    private javax.swing.JButton btnEditarProductoVenta;
    private javax.swing.JButton btnEliminarProductoVenta;
    private javax.swing.JButton btnImprimirVenta;
    private javax.swing.JButton btnRegresarVenta;
    private javax.swing.JButton btnSalirVenta;
    private javax.swing.JButton btnVerPDFventa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtVentas;
    private javax.swing.JLabel lblCantidadProductoBuscarVenta;
    private javax.swing.JLabel lblDescripcionBuscarVenta;
    private javax.swing.JLabel lblIdProductoAgregarVenta;
    private javax.swing.JLabel lblIdProductoBuscarVenta;
    private javax.swing.JLabel lblIdProductoEliminarVenta;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblNombreProductoBuscarVenta;
    private javax.swing.JLabel lblNombreProductoEliminarVenta;
    private javax.swing.JLabel lblPrecioProductoBuscarVenta;
    private javax.swing.JLabel lblSistemaVenta;
    private javax.swing.JPanel panAgregarProductosVenta;
    private javax.swing.JPanel panBuscarEditarProductoVenta;
    private javax.swing.JPanel panEliminarProductoVenta;
    private javax.swing.JPanel panFondo;
    private javax.swing.JTextField txtCantidadAgregarVenta;
    private javax.swing.JTextField txtCantidadBuscarVenta;
    private javax.swing.JLabel txtCantidadProductosVenta;
    private javax.swing.JTextField txtDescripcionProductoBuscarVenta;
    private javax.swing.JTextField txtIdProductoBuscarVenta;
    private javax.swing.JTextField txtIdProductoEliminarVenta;
    private javax.swing.JTextField txtIdProductoVenta;
    private javax.swing.JTextField txtNombreProductoBuscarVenta;
    private javax.swing.JTextField txtNombreProductoEliminarVenta;
    private javax.swing.JTextField txtPrecioProductoBuscarVenta;
    // End of variables declaration//GEN-END:variables
}
